CREATE TABLE IF NOT EXISTS packing_lists (
  id INT AUTO_INCREMENT PRIMARY KEY,
  container VARCHAR(255) NOT NULL,
  client VARCHAR(255) NOT NULL,
  proforma VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  status VARCHAR(255) NOT NULL DEFAULT 'Planifié',
  notes TEXT NULL,
  navalock VARCHAR(255) NULL,
  volume VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS packing_list_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  packing_list_id INT NOT NULL,
  pal_no VARCHAR(255) NOT NULL,
  type_pal VARCHAR(255) NOT NULL DEFAULT '_',
  pal_kgs DECIMAL(10, 2) NULL,
  status VARCHAR(255) NOT NULL DEFAULT 'planifie',
  statut_pal VARCHAR(255) NOT NULL DEFAULT '_',
  designation VARCHAR(255) NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  boxes INT NOT NULL DEFAULT 0,
  pieces INT NOT NULL DEFAULT 0,
  `order` INT NOT NULL DEFAULT 0,
  batch_nbr VARCHAR(255) NULL,
  manufacturing_date DATE NULL,
  expiry_date DATE NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_packing_items_header
    FOREIGN KEY (packing_list_id) REFERENCES packing_lists(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weight_set_packing_list (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_packing_list INT NOT NULL,
  Item VARCHAR(255) NOT NULL,
  Qty INT NOT NULL,
  Total_weight FLOAT NOT NULL,
  Unit_value FLOAT NOT NULL,
  Total_Value FLOAT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_weight_set_header
    FOREIGN KEY (id_packing_list) REFERENCES packing_lists(id) ON DELETE CASCADE
);
